### ISSUE TITLE
Не работает сборка С проекта в докере ubuntu 18/19, debian:latest

### ISSUE THREAD

**Issue by justefg** [fluencelabs/tutorials#2]
Пытались собрать hello-world а в докере с указанными выше версиями
линукса с помощью [wasi](https://github.com/CraneStation/wasi-sysroot), линковщик "замирал" по неведомым причинам. Попробовали убрать флаг --export, но там появились другие проблемы.

**Comment by michaelvoronov** [comment]
This bug was already [fixed](https://bugs.llvm.org/show_bug.cgi?id=41508) on the llvm repository and this change will be included in the llvm 8.0.1 release. Anyway, we have a separate [issue](https://github.com/fluencelabs/fluence/issues/649) in the main repo to track updates on it.
